name: 버그 리포트
description: Report a bug.
title: "[Bug]: "
labels: ["type/bug"]
body:
  - type: markdown
    attributes:
      value: |
        상황을 자세하게 알려주세요.
  - type: dropdown
    id: Domain
    attributes:
      label: 문제 영역
      description: 어떤 도메인에서 문제가 발생했습니까?
      options:
        - 동기화
        - 추가
        - 수급자
        - 요보사
        - 기관
        - 태그내역
    validations:
      required: true
  - type: input
    id: longterm-module-version
    attributes:
      label: 하이케어 버전
      description: 버그가 발생한 하이케어의 버전 정보를 알려주세요.
      placeholder: ex. 4.4.1
    validations:
      required: true
  - type: dropdown
    id: prod-or-dev
    attributes:
      label: 구동 환경
      description: 버그 발생시 구동 환경이 prod/dev인지 알려주세요.
      options:
        - 'Yes'
        - 'No'
    validations:
      required: true
  - type: input
    id: host-os
    attributes:
      label: Host OS
      description: PC 운영체제를 알려주세요. Windows는 생략하시면 됩니다.
      placeholder: e.g. Windows, Mac OS
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: 버그 설명
      description: 버그 상황을 간단하게 묘사해주세요.
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Log output
      description: 로그를 갖고 계신 경우 첨부해주시면 감사하겠습니다.
      render: shell
  - type: textarea
    id: additional-information
    attributes:
      label: 기타 부연설명
      description: 이미지나 링크 등 기타 설명을 첨부해주세요.
